version: '2'

services:

  load_balancer:
    image: dockercloud/haproxy
    links:
      - todolist
    networks:
      - dmz
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  todolist:
    image: to-do-list
    expose:
      - "8080"
      - "8081"
    environment:
      # Point to the docker load-balanced DNS alias for the ES cluster
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      # TODO Default credentials for x-pack
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "changeme"
      EXCLUDE_PORTS: 8081
    networks:
      - dmz
      - elk
    depends_on:
      - elasticsearch

  elasticsearch:
    build: elasticsearch/
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200"
      - "9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type : zen
      discovery.zen.ping.unicast.hosts: elasticsearch
    networks:
      - elk

  logstash:
    build: logstash/
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge

  dmz:
    driver: bridge
